### ISSUE TITLE
Debian не удаётся запустить плагин

### ISSUE THREAD

**Issue by anterkin** [southbridgeio/redmine_recurring_tasks#46]
```
# Logfile created on 2018-10-18 10:15:07 +0700 by logger.rb/v1.2.7
E, [2018-10-18T10:15:07.861992 #30323] ERROR -- : Validation failed: Taggings is invalid
E, [2018-10-18T10:15:07.862099 #30323] ERROR -- : /var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/validations.rb:79:in `rais
e_record_invalid'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/validations.rb:43:in `save!'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/transactions.rb:291:in `block in save!'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transac
tion'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/transactions.rb:220:in `transaction'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/transactions.rb:291:in `save!'
/var/www/redmine/plugins/redmine_recurring_tasks/app/models/recurring_task.rb:120:in `tap'
/var/www/redmine/plugins/redmine_recurring_tasks/app/models/recurring_task.rb:120:in `copy_issue'
/var/www/redmine/plugins/redmine_recurring_tasks/app/models/recurring_task.rb:126:in `execute'
/var/www/redmine/plugins/redmine_recurring_tasks/lib/redmine_recurring_tasks/issue_checker.rb:16:in `block in call'
/var/www/redmine/plugins/redmine_recurring_tasks/lib/redmine_recurring_tasks/issue_checker.rb:14:in `each'
/var/www/redmine/plugins/redmine_recurring_tasks/lib/redmine_recurring_tasks/issue_checker.rb:14:in `call'
/var/www/redmine/plugins/redmine_recurring_tasks/lib/tasks/process.rake:5:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `block in execute'
/var/lib/gems/2.3.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `each'
/var/lib/gems/2.3.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `execute'
/var/lib/gems/2.3.0/gems/rake-12.3.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/var/lib/gems/2.3.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/var/lib/gems/2.3.0/gems/rake-12.3.0/lib/rake/task.rb:181:in `invoke'
/var/lib/gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:160:in `invoke_task'
/var/lib/gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/var/lib/gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `each'
/var/lib/gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block in top_level'
/var/lib/gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:125:in `run_with_threads'
/var/lib/gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:110:in `top_level'
/var/lib/gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:83:in `block in run'
/var/lib/gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'

```
Всё перепробовали, не знаем куда копать :(

**Comment by olemskoi** [comment]
Пожалуйста, покажите вывод команды

 ls -laF plugins

Переоткройте задачу, если готовы работать по ней.
