### ISSUE TITLE
Redmine 4.1 issue

### ISSUE THREAD

**Issue by sphereweb83** [southbridgeio/redmine_recurring_tasks#62]
bundle exec rake redmine:plugins:migrate RAILS_ENV=production
rake aborted!
NoMethodError: undefined method `attr_accessible' for #<Class:0x000055556080c090>
Did you mean?  attr_accessor
/opt/bitnami/apps/redmine/htdocs/plugins/recurring_tasks/app/models/recurring_task.rb:7:in `<class:RecurringTask>'
/opt/bitnami/apps/redmine/htdocs/plugins/recurring_tasks/app/models/recurring_task.rb:1:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/config/environment.rb:16:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/plugins/recurring_tasks/lib/tasks/recurring_tasks.rake:7:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/lib/tasks/redmine.rake:202:in `block in <top (required)>'
/opt/bitnami/apps/redmine/htdocs/lib/tasks/redmine.rake:202:in `each'
/opt/bitnami/apps/redmine/htdocs/lib/tasks/redmine.rake:202:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/Rakefile:7:in `<top (required)>'
/opt/bitnami/ruby/bin/bundle:23:in `load'
/opt/bitnami/ruby/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)

**Comment by funk-yourself** [comment]
Hello! Which version of plugin are you using? There's no `attr_accessible` usage in current version: https://github.com/southbridgeio/redmine_recurring_tasks/blob/master/app/models/recurring_task.rb

**Comment by gainskills** [comment]
@sphereweb83 , I'm using https://github.com/gainskills/redmine/tree/master/4.1/alpine , the plugin works properly. Hope this helps.
Thanks,
